### PR TITLE
1 - Adding the Classification to AutoML Model

### LINKED ISSUE #1: Add Classification to AutoML Model
### Problem Statement
I want to enhance my Streamlit app that uses PyCaret for automatic regression analysis. Currently, the app only supports regression analysis, but I want to add the functionality to choose between regression and classification.

### Steps to Reproduce
1. Open the Streamlit app.
2. Select the target variable.
3. Choose whether to run regression or classification analysis.
4. Verify that the selected analysis is executed correctly.

### Expected Behavior
The app should allow the user to select the target variable and choose between regression and classification analysis. It should then execute the selected analysis accordingly.

### PR DESCRIPTION
**Pull request by ZaibyS**

### CODE REVIEW

**Comment by ZaibyS** [comment]
@espin086 
I've incorporated the classification code and conducted initial testing using the iris dataset. Tomorrow, I plan to extend the testing with more datasets both for regression and classification.

**Comment by ZaibyS** [comment]
@espin086 
Today, I conducted tests on the application using datasets for both classification and regression. 
The testing was performed on the following datasets:
1. Iris: https://archive.ics.uci.edu/dataset/53/iris (For classification used  `class` as the target variable)
2. Wine Quality: https://archive.ics.uci.edu/dataset/186/wine+quality (For classification used `quality` column as the target variable and for regression used `volatile acidity` as the target variable)
3. Mushroom classification: https://archive.ics.uci.edu/dataset/73/mushroom (For classification used `poisonous`  as the target column)
4. Census Income: https://archive.ics.uci.edu/dataset/20/census+income (For classification used `income` as the target column)

**Comment by espin086** [comment]
@ZaibyS  - not sure why it didn’t work with this dataset, can you see why? 
Screenshot 2024-02-14 at 10 30 22 AM
[CourseraDataset-Clean.csv](https://github.com/espin086/AutoLearn/files/14284825/CourseraDataset-Clean.csv)

**Comment by espin086** [comment]
@ZaibyS - I tested the addition of the classification and regression on other datasets and it works great. I am going to merge this pull request and if any bugs come up like the one I commented about, I’ll create a different issue, but this looks good to go, thank you

**Pull request merged**
